---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "25"
year: "2014"
contributor: 
- "Susanne Brandt"
title: "Lieder und Gedichte sammeln gegen das Verstummen. Erinnerungen an die Bibliothekarin Anna Kvapilová (1905-1992)"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100219254"
date: 2014-07-19 15:29
comments: false
sharing: true
footer: true

---