---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "25"
year: "2014"
contributor: 
- "Karin Alexander"
title: "Die Frau im Bibliothekskatalog"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100219239"
date: 2014-07-19 15:29
comments: false
sharing: true
footer: true

---