---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "25"
year: "2014"
contributor: 
- "Katharina Leyrer"
title: "Das Geschlecht spukt in der Stadtbibliothek: Ein Aufruf für genderneutrale Bibliotheksangebote"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100219295"
date: 2014-07-19 15:29
comments: false
sharing: true
footer: true

---