---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "25"
year: "2014"
contributor: 
- "Marion Voigt"
title: "Wiberat. Eine Frauengestalt aus dem Frühmittelalter als Patronin der Bibliothekare und Bibliophilen. Oder: Feiern Sie den 2. Mai?"
subtitle: ""
urn: "urn:nbn:de:kobv:11-100219277"
date: 2014-07-19 15:29
comments: false
sharing: true
footer: true

---